'use client';
import React, { useMemo, useState, useEffect, useRef } from 'react';
import { KeyboardContainer } from '@/components/keyboard/KeyboardContainer';
import { useRouter } from 'next/navigation';
import type { Preset, PresetApiResponse, Segment } from '@/types/preset';
import SegmentEditor from './SegmentEditor';
import SegmentTimeline from './SegmentTimeline';
import generateAutoName from './utils';

type SegmentWithTimes = Segment & { start: number; end: number };

export default function PresetForm({
  defaultVisibility = 'private',
  currentUserRole = null,
  onSubmit,
  initialValues,
  edit = false,
  onCancel,
  lockVisibility = false,
}: {
  defaultVisibility?: 'private' | 'public';
  currentUserRole?: string | null;
  onSubmit?: (data: Preset) => void;
  initialValues?: Partial<Preset> & { segments?: Segment[] };
  edit?: boolean;
  onCancel?: () => void;
  lockVisibility?: boolean;
}) {
  const router = useRouter();
  const [tagInput, setTagInput] = useState('');
  const [formValues, setFormValues] = useState(() => ({
    name: initialValues?.name ?? '',
    difficulty: (initialValues?.difficulty as 'easy' | 'moderate' | 'hard') ?? 'moderate',
    tags: Array.isArray(initialValues?.tags)
      ? (initialValues?.tags as string[])
      : typeof initialValues?.tags === 'string'
        ? (initialValues.tags || '').split(',').filter(Boolean)
        : [],
    visibilityState:
      (initialValues?.visibility as 'private' | 'public') ??
      (defaultVisibility as 'private' | 'public'),
    segments: (initialValues?.segments || [null]).map((s) =>
      s
        ? ({
            id: (s as Segment).id,
            position: (s as Segment).position,
            name: (s as Segment).name ?? null,
            duration_seconds: (s as Segment).duration_seconds ?? 60,
            speed: (s as Segment).speed ?? 3,
            incline: (s as Segment).incline ?? 0,
          } as Segment)
        : ({ name: null, duration_seconds: 60, speed: 3, incline: 0 } as Segment)
    ) as Segment[],
  }));

  const isAdmin = currentUserRole === 'admin';
  const isLocked = Boolean(lockVisibility);
  const visibility = isAdmin ? formValues.visibilityState : 'private';
  const [submitting, setSubmitting] = useState(false);
  type ErrorsState = {
    _form?: string;
    name?: string;
    segments?: Record<number, Record<string, string>>;
    [key: string]: string | Record<number, Record<string, string>> | undefined;
  };
  const [errors, setErrors] = useState<ErrorsState>({});
  const [showCustomNameModal, setShowCustomNameModal] = useState(false);
  const [tempCustomName, setTempCustomName] = useState('');
  const customNameRef = useRef<HTMLInputElement | null>(null);
  const [isNameEdited, setIsNameEdited] = useState(false);

  const segments = formValues.segments;

  const timeline = useMemo(() => {
    return segments.reduce((acc: SegmentWithTimes[], s) => {
      const start = acc.length ? acc[acc.length - 1].end : 0;
      const end = start + (s.duration_seconds || 0);
      acc.push({ ...(s as Segment), start, end });
      return acc;
    }, [] as SegmentWithTimes[]);
  }, [segments]);

  const total = useMemo(
    () => segments.reduce((a, b) => a + (b.duration_seconds || 0), 0),
    [segments]
  );

  // auto-generate name from duration + difficulty for create flows when name is empty
  // Note: we intentionally do not mark the existing preset name as "edited"
  // on mount. This allows the edit form to show live autogenerated name
  // updates as segments/duration change. The name will stop auto-updating
  // once the user explicitly edits the name field.

  // Derive the displayed name: autogenerated from total/difficulty unless
  // the user has manually edited it, in which case use formValues.name.
  const derivedName = useMemo(() => {
    if (isNameEdited) return formValues.name;
    return generateAutoName(total, formValues.difficulty as 'easy' | 'moderate' | 'hard');
  }, [isNameEdited, formValues.name, total, formValues.difficulty]);

  useEffect(() => {
    if (showCustomNameModal) {
      const prev = document.body.style.overflow;
      document.body.style.overflow = 'hidden';
      return () => {
        document.body.style.overflow = prev;
      };
    }
    return;
  }, [showCustomNameModal]);

  function validate() {
    const newErrs: ErrorsState = {};
    if (!formValues.name || !formValues.name.trim()) newErrs.name = 'Name is required';
    if (!segments || segments.length === 0) newErrs._segments = 'At least one segment is required';

    const segErrs: Record<number, Record<string, string>> = {};
    segments.forEach((s, i) => {
      const e: Record<string, string> = {};
      if (!s.duration_seconds || Number(s.duration_seconds) < 1)
        e.duration = 'Duration must be at least 1 second';
      if (s.speed == null || Number(s.speed) < 0 || Number(s.speed) > 10)
        e.speed = 'Speed must be between 0 and 10';
      else if (Math.abs(Number(s.speed) * 2 - Math.round(Number(s.speed) * 2)) > 1e-6)
        e.speed = 'Speed must be a multiple of 0.5';
      if (s.incline == null || Number(s.incline) < 0 || Number(s.incline) > 10)
        e.incline = 'Incline must be between 0 and 10';
      if (Object.keys(e).length) segErrs[i] = e;
    });
    if (Object.keys(segErrs).length) newErrs.segments = segErrs;

    setErrors(newErrs);
    return Object.keys(newErrs).length === 0;
  }

  async function handleCreate(e?: React.FormEvent) {
    e?.preventDefault();
    if (!validate()) return;
    const payload = {
      name: derivedName.trim(),
      visibility,
      tags: formValues.tags,
      difficulty: formValues.difficulty,
      segments: segments.map((seg) => ({
        name: seg.name ?? null,
        duration_seconds: seg.duration_seconds,
        speed: seg.speed,
        incline: seg.incline,
      })),
    };
    setSubmitting(true);
    setErrors({});
    (async () => {
      try {
        let res: Response;
        let parsed: PresetApiResponse | null = null;
        if (edit && initialValues && initialValues.id) {
          res = await fetch(`/api/presets/${initialValues.id}`, {
            method: 'PATCH',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(payload),
          });
          const text = await res.text();
          try {
            parsed = text ? JSON.parse(text) : null;
          } catch (err) {
            parsed = { text } as unknown as PresetApiResponse;
          }
          if (!res.ok) {
            const newErrs: ErrorsState = {};
            if ((parsed as any)?.details && (parsed as any).details.fieldErrors) {
              const fe = (parsed as any).details.fieldErrors;
              if (fe.segments && Array.isArray(fe.segments)) {
                const segErrs: Record<number, Record<string, string>> = {};
                (fe.segments as unknown[]).forEach((entry, idx: number) => {
                  if (entry && typeof entry === 'object') {
                    Object.entries(entry as Record<string, unknown>).forEach(([k, v]) => {
                      segErrs[idx] = segErrs[idx] || {};
                      segErrs[idx][k] = Array.isArray(v) ? String((v as any)[0]) : String(v);
                    });
                  }
                });
                if (Object.keys(segErrs).length) newErrs.segments = segErrs;
              }
              Object.entries(fe).forEach(([k, v]) => {
                if (k === 'segments') return;
                if (Array.isArray(v) && (v as any)[0]) newErrs[k] = (v as any)[0];
                else if (typeof v === 'string') newErrs[k] = v as string;
              });
            }
            if (
              (parsed as any)?.details &&
              (parsed as any).details.formErrors &&
              (parsed as any).details.formErrors.length
            ) {
              newErrs._form = (parsed as any).details.formErrors.join('; ');
            } else if ((parsed as any)?.error) {
              newErrs._form = (parsed as any).error as string;
            }
            setErrors(newErrs);
            setSubmitting(false);
            return;
          }
          setErrors({});
          try {
            const refetch = await fetch(`/api/presets/${initialValues.id}`);
            if (refetch.ok) {
              const fresh = await refetch.json();
              if (onSubmit) onSubmit(fresh);
              return;
            }
            if (onSubmit && parsed) onSubmit(parsed as unknown as Preset);
            return;
          } catch (e) {
            if (onSubmit && parsed) onSubmit(parsed as unknown as Preset);
            return;
          }
        }

        res = await fetch('/api/presets', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(payload),
        });
        const text = await res.text();
        try {
          parsed = text ? JSON.parse(text) : null;
        } catch (err) {
          parsed = { text } as unknown as PresetApiResponse;
        }

        if (!res.ok) {
          const newErrs: ErrorsState = {};
          if ((parsed as any)?.details && (parsed as any).details.fieldErrors) {
            const fe = (parsed as any).details.fieldErrors;
            if (fe.segments && Array.isArray(fe.segments)) {
              const segErrs: Record<number, Record<string, string>> = {};
              (fe.segments as unknown[]).forEach((entry, idx: number) => {
                if (entry && typeof entry === 'object') {
                  Object.entries(entry as Record<string, unknown>).forEach(([k, v]) => {
                    segErrs[idx] = segErrs[idx] || {};
                    segErrs[idx][k] = Array.isArray(v) ? String((v as any)[0]) : String(v);
                  });
                }
              });
              if (Object.keys(segErrs).length) newErrs.segments = segErrs;
            }
            Object.entries(fe).forEach(([k, v]) => {
              if (k === 'segments') return;
              if (Array.isArray(v) && (v as any)[0]) newErrs[k] = (v as any)[0];
              else if (typeof v === 'string') newErrs[k] = v as string;
            });
          }

          if (
            (parsed as any)?.details &&
            (parsed as any).details.formErrors &&
            (parsed as any).details.formErrors.length
          ) {
            newErrs._form = (parsed as any).details.formErrors.join('; ');
          } else if ((parsed as any)?.error) {
            newErrs._form = (parsed as any).error as string;
          }

          setErrors(newErrs);
          setSubmitting(false);
          return;
        }

        setErrors({});
        const newId = (parsed as any)?.id;
        if (newId) {
          router.push(`/dashboard/presets/${newId}`);
          return;
        }
        router.push('/dashboard/presets');
      } catch (err) {
        setErrors({
          _form: err instanceof Error ? err.message : 'Submission failed. Please try again.',
        });
      } finally {
        setSubmitting(false);
      }
    })();
  }

  function saveCustomName() {
    if (tempCustomName && tempCustomName.trim()) {
      setFormValues((p) => ({ ...p, name: tempCustomName.trim() }));
      setIsNameEdited(true);
    }
    setShowCustomNameModal(false);
  }

  function cancelCustomName() {
    setTempCustomName('');
    setShowCustomNameModal(false);
  }

  return (
    <form onSubmit={handleCreate} className="space-y-4">
      <div className="grid grid-cols-12 gap-8">
        <div className="col-span-8 space-y-6">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 items-end">
            <div className="md:col-span-2">
              <label htmlFor="preset-name" className="block text-2xl font-semibold">
                Name *
              </label>
              <input
                id="preset-name"
                className="w-full border px-8 py-6 rounded text-2xl"
                value={derivedName}
                onChange={(e) => {
                  setFormValues((p) => ({ ...p, name: e.target.value }));
                  setIsNameEdited(true);
                }}
              />
              {errors.name ? <div className="text-xl text-red-600">{errors.name}</div> : null}
            </div>

            <div className="md:col-span-1">
              <label htmlFor="preset-difficulty" className="block text-2xl font-semibold">
                Difficulty
              </label>
              <select
                value={formValues.difficulty}
                onChange={(e) =>
                  setFormValues((p) => ({
                    ...p,
                    difficulty: e.target.value as 'easy' | 'moderate' | 'hard',
                  }))
                }
                className="w-full border px-8 py-6 rounded text-2xl"
                id="preset-difficulty"
              >
                <option value="easy">Easy</option>
                <option value="moderate">Moderate</option>
                <option value="hard">Hard</option>
              </select>
            </div>
          </div>

          {errors._form ? <div className="text-xl text-red-600">{errors._form}</div> : null}

          <div className="mt-4 border rounded p-4">
            <h3 className="font-medium">Segments</h3>
            <SegmentEditor
              segments={segments}
              onChange={(s) =>
                setFormValues((p) => {
                  const totalForS = s.reduce((a, b) => a + (b.duration_seconds || 0), 0);
                  const auto = !isNameEdited
                    ? generateAutoName(totalForS, p.difficulty as 'easy' | 'moderate' | 'hard')
                    : p.name;
                  return { ...p, segments: s, name: auto };
                })
              }
              editable
              errors={errors.segments ?? null}
              showDurationInMinutes
            />
          </div>
        </div>

        <div className="col-span-4">
          {/* Timeline preview box removed when editing — show only for create flows */}
          {!edit ? (
            <div className="col-span-4">
              <SegmentTimeline segments={segments} />
            </div>
          ) : null}
        </div>
      </div>

      {/* Inline modal for entering custom preset name (touch-friendly) */}
      {showCustomNameModal ? (
        <div className="fixed inset-0 z-50 flex items-end sm:items-center justify-center">
          <button
            type="button"
            aria-label="Close"
            className="absolute inset-0 bg-black/50 cursor-default"
            onClick={cancelCustomName}
            onKeyDown={(e) => e.key === 'Escape' && cancelCustomName()}
          />
          <div className="relative w-full sm:w-96 bg-white rounded-t-lg sm:rounded-lg p-4 m-4">
            <div className="flex items-center justify-between mb-2">
              <h3 className="text-lg font-medium">Custom Preset Name</h3>
              <button type="button" onClick={cancelCustomName} className="text-gray-500">
                ✕
              </button>
            </div>
            <form
              onSubmit={(e) => {
                e.preventDefault();
                saveCustomName();
              }}
            >
              <input
                ref={(el) => {
                  customNameRef.current = el;
                }}
                className="w-full border px-6 py-4 rounded text-2xl"
                placeholder="Enter name"
                value={tempCustomName}
                onChange={(e) => setTempCustomName(e.target.value)}
                onInput={() => setIsNameEdited(true)}
                aria-label="Custom preset name"
              />

              <div className="mt-3">
                <KeyboardContainer
                  mode="username"
                  onKey={(k) => setTempCustomName((s) => s + k)}
                  onBackspace={() => setTempCustomName((s) => s.slice(0, -1))}
                  onCancel={cancelCustomName}
                  onEnter={saveCustomName}
                />
              </div>

              <div className="mt-3 flex justify-end gap-3">
                <button
                  type="button"
                  onClick={cancelCustomName}
                  className="px-6 py-4 rounded bg-gray-100 text-2xl"
                >
                  Cancel
                </button>
                <button type="submit" className="px-6 py-4 rounded bg-blue-600 text-white text-2xl">
                  Save
                </button>
              </div>
            </form>
          </div>
        </div>
      ) : null}

      <div className="flex gap-2">
        <button
          type="button"
          onClick={() => {
            if (edit && onCancel) onCancel();
            else router.back();
          }}
          className="px-4 py-3 bg-gray-200 rounded text-lg"
        >
          Cancel
        </button>
        <button
          type="submit"
          disabled={submitting}
          className="px-4 py-3 bg-blue-600 text-white rounded text-lg"
        >
          {submitting
            ? edit
              ? 'Saving...'
              : 'Creating...'
            : edit
              ? 'Save Changes'
              : 'Create Preset'}
        </button>
      </div>
    </form>
  );
}
