'use client';
import React, { useContext, useEffect, useMemo, useState, useLayoutEffect, useRef } from 'react';
import PresetRunnerContext from '@/context/PresetRunnerContext';
import { useRouter } from 'next/navigation';
import type { Preset, PresetApiResponse, Segment } from '@/types/preset';
import SegmentEditor from './SegmentEditor';
import SegmentTimeline from './SegmentTimeline';
import PresetForm from './PresetForm';
import generateAutoName from './utils';
import TimelineBar from './TimelineBar.tsx';
import SegmentCard from './SegmentCard.tsx';
import { useErrorStore } from '@/stores';

type SegmentWithTimes = Segment & { start: number; end: number };

function formatTime(s: number) {
  const m = Math.floor(s / 60);
  const sec = s % 60;
  return `${m}m ${sec}s`;
}

export default function PresetDetail({
  id,
  initialPreset,
  currentUserId,
  currentUserRole,
}: {
  id: number;
  initialPreset?: Preset | null;
  currentUserId?: number | null;
  currentUserRole?: string | null;
}) {
  const router = useRouter();
  const [preset, setPreset] = useState<Preset | null>(initialPreset ?? null);
  const [editing, setEditing] = useState(false);
  const [segments, setSegments] = useState<Segment[]>(initialPreset?.segments || []);
  const [saving, setSaving] = useState(false);
  const [deleting, setDeleting] = useState(false);
  const [copying, setCopying] = useState(false);
  const [deleteError, setDeleteError] = useState<string | null>(null);
  const pushError = useErrorStore((state) => state.push);

  // access runner context if available (tests may render without provider)
  const runnerCtx = useContext(PresetRunnerContext);
  const startPresetFromRunner = runnerCtx?.startPreset ?? (async () => {});
  const [starting, setStarting] = useState(false);

  useEffect(() => {
    // if initial preset provided from server, skip client fetch
    if (initialPreset) return;
    fetch(`/api/presets/${id}`)
      .then((r) => r.json())
      .then((data) => {
        setPreset((data as Preset) || null);
        setSegments((data?.segments || []) as Segment[]);
      })
      .catch(() => setPreset(null));
  }, [id, initialPreset]);

  const timeline = useMemo(() => {
    return segments.reduce((acc: SegmentWithTimes[], s) => {
      const start = acc.length ? acc[acc.length - 1].end : 0;
      const end = start + (s.duration_seconds || 0);
      acc.push({ ...(s as Segment), start, end });
      return acc;
    }, [] as SegmentWithTimes[]);
  }, [segments]);

  const total = useMemo(
    () => segments.reduce((a, b) => a + (b.duration_seconds || 0), 0),
    [segments]
  );

  // Derive the displayed preset name: always autogenerated while editing so
  // it stays in sync with current segments/difficulty without calling setState
  // inside an effect.
  const displayName = useMemo(() => {
    if (editing && preset) {
      return generateAutoName(total, preset.difficulty ?? 'moderate');
    }
    return preset?.name ?? '';
  }, [editing, total, preset]);

  // Pagination for timeline/details (keep in sync with TimelineBar)
  const perPage = 3;
  const [page, setPage] = useState(0);
  const prevLen = useRef(segments.length);
  useLayoutEffect(() => {
    if (segments.length > prevLen.current) {
      const lastPage = Math.floor((segments.length - 1) / perPage);
      setPage(lastPage);
    }
    prevLen.current = segments.length;
  }, [segments.length, perPage]);

  // segment editing logic delegated to SegmentEditor via setSegments

  async function save() {
    if (!preset) return;
    setSaving(true);
    try {
      const body = {
        name: displayName,
        tags: preset.tags ? String(preset.tags).split(',').filter(Boolean) : [],
        difficulty: preset.difficulty,
        segments: segments.map((seg, i) => ({
          position: i,
          name: seg.name,
          duration_seconds: seg.duration_seconds,
          speed: seg.speed,
          incline: seg.incline,
        })),
      };
      const res = await fetch(`/api/presets/${preset.id}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body),
      });
      const text = await res.text();
      let parsed: PresetApiResponse | null = null;
      try {
        parsed = text ? JSON.parse(text) : null;
      } catch (e) {
        parsed = { text };
      }
      if (!res.ok) {
        // show server error if provided
        const msg =
          parsed && (parsed.error || parsed.message)
            ? parsed.error || parsed.message
            : `Status ${res.status}`;
        console.error('Save failed response:', res.status, parsed);
        pushError({ title: 'Save Failed', message: msg });
        // Throw a sentinel error so catch block knows this was already handled
        throw new Error('ServerErrorHandled');
      }
      // PATCH response already includes the full updated preset + segments
      const savedPreset = parsed as Preset;
      setPreset(savedPreset || null);
      setSegments((savedPreset?.segments || []) as Segment[]);
      setEditing(false);
    } catch (e) {
      console.error(e);
      // Only show generic error if it wasn't intentionally thrown with a message already pushed
      if (!(e instanceof Error && (e.message === 'Cancel' || e.message === 'ServerErrorHandled'))) {
        pushError({ title: 'Save Failed', message: 'An unexpected error occurred.' });
      }
    } finally {
      setSaving(false);
    }
  }

  async function handleDelete() {
    if (!preset) return;
    setDeleteError(null);
    const ok = confirm('Are you sure you want to delete this preset?');
    if (!ok) return;
    setDeleting(true);
    try {
      const res = await fetch(`/api/presets/${preset.id}`, { method: 'DELETE' });
      if (!res.ok) {
        const text = await res.text();
        let parsed: PresetApiResponse | null = null;
        try {
          parsed = text ? JSON.parse(text) : null;
        } catch (e) {
          parsed = { text };
        }
        const msg = (parsed && (parsed.error || parsed.message)) || `Status ${res.status}`;
        setDeleteError(String(msg));
        setDeleting(false);
        return;
      }
      // clear deleting state then redirect to list
      setDeleting(false);
      router.push('/dashboard/presets');
    } catch (err) {
      console.error('Failed to delete preset', err);
      setDeleteError('Failed to delete preset. Please try again.');
      setDeleting(false);
    }
  }

  async function handleCopyPreset() {
    if (!preset) return;
    setCopying(true);
    try {
      const createBody = {
        name: generateAutoName(total, preset.difficulty ?? 'moderate'),
        visibility: 'private',
        tags: preset.tags ? String(preset.tags).split(',').filter(Boolean) : [],
        difficulty: preset.difficulty ?? 'moderate',
        segments: segments.map((seg, i) => ({
          position: i,
          name: seg.name ?? null,
          duration_seconds: seg.duration_seconds,
          speed: seg.speed,
          incline: seg.incline,
        })),
      };
      const createRes = await fetch('/api/presets', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(createBody),
      });
      const createText = await createRes.text();
      let createParsed: PresetApiResponse | null = null;
      try {
        createParsed = createText ? JSON.parse(createText) : null;
      } catch (e) {
        createParsed = { text: createText };
      }
      if (!createRes.ok) {
        pushError({
          title: 'Copy Failed',
          message: `${(createParsed && (createParsed.error || createParsed.message)) || createRes.status}`,
        });
        return;
      }
      // POST now returns the created preset (including authorId & segments).
      const createdPreset = (createParsed as Preset) || null;
      const newId = createdPreset?.id || createParsed?.id;
      if (newId) {
        // If the response contains an authorId, we can immediately navigate.
        // If not, attempt to re-fetch the preset once to ensure server persisted ownership.
        if (createdPreset && typeof createdPreset.authorId !== 'undefined') {
          router.push(`/dashboard/presets/${newId}`);
        } else {
          // fallback: fetch the preset once then navigate
          try {
            const check = await fetch(`/api/presets/${newId}`);
            if (check.ok) {
              router.push(`/dashboard/presets/${newId}`);
            } else {
              // still navigate — server may resolve on full reload
              router.push(`/dashboard/presets/${newId}`);
            }
          } catch (e) {
            router.push(`/dashboard/presets/${newId}`);
          }
        }
      }
    } catch (err) {
      console.error('Failed to create copy', err);
      pushError({ title: 'Copy Failed', message: 'An unexpected error occurred.' });
    } finally {
      setCopying(false);
    }
  }

  const calories = useMemo(() => {
    // naive: sum(duration_minutes * MET * weight(70kg) * 0.0175)
    // approximate MET from speed
    const minutes = total / 60;
    const met =
      segments.reduce((acc, s) => {
        const sp = s.speed || 3;
        const m = sp >= 8 ? 10 : sp >= 6 ? 8 : sp >= 4 ? 6 : 3.5;
        return acc + ((m * (s.duration_seconds || 0)) / total || 0);
      }, 0) || 5;
    return Math.round(minutes * met * 70 * 0.0175);
  }, [segments, total]);

  const isAdmin = currentUserRole === 'admin';
  const isOwner = Boolean(preset && currentUserId != null && preset.authorId === currentUserId);
  // allow editing when user owns the preset or when user is an admin
  const canEdit = Boolean(isOwner || isAdmin);

  function cancelEditing() {
    // revert any local changes and exit edit mode
    setSegments((preset?.segments || []) as Segment[]);
    setEditing(false);
  }

  if (!preset) return <div>Loading preset...</div>;

  const handleStart = async () => {
    if (!preset) return;
    setStarting(true);
    try {
      await startPresetFromRunner(preset);
    } catch (e) {
      console.error('Failed to start preset', e);
      pushError({ title: 'Start Failed', message: 'Failed to start preset.' });
    } finally {
      setStarting(false);
    }
  };

  return (
    <div className="space-y-3">
      <div className="-mt-2 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3 pb-3 border-b border-gray-200">
        {/* Left: title + subtitle */}
        <div className="min-w-0">
          <div className="flex items-center gap-3">
            <h2 className="text-4xl font-bold text-gray-900 truncate">{displayName}</h2>
            {editing && canEdit ? (
              <select
                value={preset.difficulty ?? 'moderate'}
                onChange={(e) => {
                  const newDiff = e.target.value as 'easy' | 'moderate' | 'hard';
                  setPreset((p) => {
                    if (!p) return p;
                    const auto = generateAutoName(total, newDiff);
                    return { ...p, difficulty: newDiff, name: auto } as Preset;
                  });
                }}
                className="ml-2 border px-3 py-2 rounded text-lg"
                aria-label="Preset difficulty"
              >
                <option value="easy">Easy</option>
                <option value="moderate">Moderate</option>
                <option value="hard">Hard</option>
              </select>
            ) : null}
            {preset.authorId == null ? (
              <span className="inline-flex items-center text-xs bg-green-100 text-green-800 px-2 py-0.5 rounded-full font-medium shrink-0">
                Public
              </span>
            ) : null}
          </div>
        </div>

        {/* Right: calories + action buttons */}
        <div className="flex flex-col sm:flex-row sm:items-center gap-2 shrink-0">
          <p className="text-sm text-gray-500 sm:text-right">
            ~<span className="font-semibold text-gray-700">{calories}</span> kcal
          </p>
          <div className="flex flex-wrap items-center gap-4">
            {/* Copy — non-owner/non-admin only */}
            {!canEdit ? (
              <button
                type="button"
                onClick={handleCopyPreset}
                disabled={copying}
                className="inline-flex items-center gap-3 px-6 py-4 text-lg font-medium rounded-lg border border-gray-300 bg-white text-gray-700 hover:bg-gray-50 hover:shadow-sm transition-all disabled:opacity-50"
              >
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="20"
                  height="20"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="2"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  aria-hidden="true"
                >
                  <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
                  <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
                </svg>
                {copying ? 'Copying…' : 'Copy'}
              </button>
            ) : null}

            {/* Edit flow: show Edit when not editing; show Save/Cancel/Delete when editing */}
            {!editing && canEdit ? (
              <button
                type="button"
                onClick={() => setEditing(true)}
                disabled={deleting}
                className="inline-flex items-center gap-3 px-6 py-4 text-lg font-medium rounded-lg border border-gray-300 bg-white text-gray-700 hover:bg-gray-50 hover:shadow-sm transition-all disabled:opacity-50"
              >
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="20"
                  height="20"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="2"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  aria-hidden="true"
                >
                  <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7" />
                  <path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z" />
                </svg>
                Edit
              </button>
            ) : null}

            {editing && canEdit ? (
              <button
                type="button"
                onClick={cancelEditing}
                disabled={saving}
                className="inline-flex items-center gap-3 px-6 py-4 text-lg font-medium rounded-lg border border-gray-300 bg-white text-gray-700 hover:bg-gray-50 hover:shadow-sm transition-all disabled:opacity-50"
              >
                Cancel
              </button>
            ) : null}

            {/* Delete — owner or admin */}
            {isOwner || isAdmin ? (
              <button
                type="button"
                onClick={handleDelete}
                disabled={deleting}
                className="inline-flex items-center gap-3 px-6 py-4 text-lg font-medium rounded-lg border border-red-300 bg-white text-red-600 hover:bg-red-50 hover:shadow-sm transition-all disabled:opacity-50"
              >
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="20"
                  height="20"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="2"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  aria-hidden="true"
                >
                  <polyline points="3 6 5 6 21 6" />
                  <path d="M19 6l-1 14a2 2 0 0 1-2 2H8a2 2 0 0 1-2-2L5 6" />
                  <path d="M10 11v6" />
                  <path d="M14 11v6" />
                  <path d="M9 6V4a1 1 0 0 1 1-1h4a1 1 0 0 1 1 1v2" />
                </svg>
                {deleting ? 'Deleting…' : 'Delete'}
              </button>
            ) : null}

            {/* Save — owner or admin */}
            {editing && canEdit ? (
              <button
                type="button"
                onClick={save}
                disabled={saving}
                className="inline-flex items-center gap-3 px-6 py-4 text-lg font-medium rounded-lg border border-blue-300 bg-white text-blue-600 hover:bg-blue-50 hover:shadow-sm transition-all disabled:opacity-50"
              >
                {saving ? (
                  <svg
                    className="animate-spin h-8 w-8"
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                  >
                    <circle
                      className="opacity-25"
                      cx="12"
                      cy="12"
                      r="10"
                      stroke="currentColor"
                      strokeWidth="4"
                    />
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v8H4z" />
                  </svg>
                ) : (
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="20"
                    height="20"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="2"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    aria-hidden="true"
                  >
                    <path d="M19 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11l5 5v11a2 2 0 0 1-2 2z" />
                    <polyline points="17 21 17 13 7 13 7 21" />
                    <polyline points="7 3 7 8 15 8" />
                  </svg>
                )}
                {saving ? 'Saving…' : 'Save'}
              </button>
            ) : null}

            {/* Start — always visible */}
            <button
              type="button"
              onClick={handleStart}
              disabled={starting}
              title="Start this preset on the treadmill"
              className="inline-flex items-center gap-3 px-8 py-4 text-lg font-semibold rounded-lg bg-green-800 text-white shadow-sm hover:bg-green-900 hover:shadow-md transition-all disabled:opacity-50"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="20"
                height="20"
                viewBox="0 0 24 24"
                fill="currentColor"
                aria-hidden="true"
              >
                <polygon points="5 3 19 12 5 21 5 3" />
              </svg>
              {starting ? 'Starting…' : 'Start'}
            </button>
          </div>
        </div>
      </div>

      <div className="border rounded p-4">
        <h3 className="font-medium">Timeline Preview</h3>
        <div className="mt-3 space-y-4">
          <TimelineBar
            timeline={timeline}
            total={total}
            page={page}
            setPage={setPage}
            perPage={perPage}
          />

          <div className="space-y-3">
            <div
              style={{ gridTemplateColumns: '40px 260px 1fr 320px 260px 260px 1fr' }}
              className="hidden sm:grid items-start gap-x-6 mb-1 px-4 py-3 rounded-lg bg-gray-50 border border-gray-100 text-base font-semibold text-gray-600 uppercase tracking-wider"
            >
              <div className="text-center">#</div>
              <div>Segment</div>
              <div />
              <div className="text-center">Duration</div>
              <div className="text-center">Speed</div>
              <div className="text-center">Incline</div>
              <div className="text-right">Actions</div>
            </div>

            {(() => {
              const start = page * perPage;
              const pageSlice = timeline.slice(start, start + perPage);
              return pageSlice.map((t, i) => {
                const idx = start + i;
                const duration = t.end - t.start;
                const sp = t.speed || 3;
                const met = sp >= 8 ? 10 : sp >= 6 ? 8 : sp >= 4 ? 6 : 3.5;
                const cal = Math.round((duration / 60) * met * 70 * 0.0175);

                return (
                  <SegmentCard
                    key={idx}
                    index={idx}
                    segment={t}
                    start={t.start}
                    calories={cal}
                    durationStep={editing ? 30 : 10}
                    readOnly={!(editing && canEdit)}
                    onChangeName={(idx, name) => {
                      setSegments((prev) => prev.map((s, si) => (si === idx ? { ...s, name } : s)));
                    }}
                    onChangeDuration={(idx, delta) => {
                      setSegments((prev) =>
                        prev.map((s, si) =>
                          si === idx
                            ? {
                                ...s,
                                duration_seconds: Math.max(1, (s.duration_seconds || 0) + delta),
                              }
                            : s
                        )
                      );
                    }}
                    onChangeSpeed={(idx, delta) => {
                      setSegments((prev) =>
                        prev.map((s, si) =>
                          si === idx
                            ? {
                                ...s,
                                speed: Math.min(
                                  7,
                                  Math.max(0, Number(((s.speed || 0) + delta).toFixed(1)))
                                ),
                              }
                            : s
                        )
                      );
                    }}
                    onChangeIncline={(idx, delta) => {
                      setSegments((prev) =>
                        prev.map((s, si) =>
                          si === idx
                            ? { ...s, incline: Math.min(15, Math.max(0, (s.incline || 0) + delta)) }
                            : s
                        )
                      );
                    }}
                    onMoveUp={(idx) => {
                      setSegments((prev) => {
                        if (idx <= 0) return prev;
                        const copy = [...prev];
                        const tmp = copy[idx - 1];
                        copy[idx - 1] = copy[idx];
                        copy[idx] = tmp;
                        return copy;
                      });
                    }}
                    onMoveDown={(idx) => {
                      setSegments((prev) => {
                        if (idx >= prev.length - 1) return prev;
                        const copy = [...prev];
                        const tmp = copy[idx + 1];
                        copy[idx + 1] = copy[idx];
                        copy[idx] = tmp;
                        return copy;
                      });
                    }}
                    onDelete={(idx) => {
                      setSegments((prev) => prev.filter((_, si) => si !== idx));
                    }}
                  />
                );
              });
            })()}

            <div className="flex justify-center mt-4">
              {editing && canEdit && (
                <button
                  type="button"
                  onClick={() =>
                    setSegments((prev) => [
                      ...prev,
                      {
                        id: Date.now(),
                        name: 'New segment',
                        duration_seconds: 30,
                        speed: 3,
                        incline: 0,
                      },
                    ])
                  }
                  className="px-4 py-2 rounded-lg border border-dashed border-gray-300 text-sm text-gray-700 hover:bg-gray-50"
                >
                  + Add Segment
                </button>
              )}
            </div>
          </div>
        </div>
      </div>

      {/* Editor section removed */}
    </div>
  );
}
